# Generated by Django 4.2.2 on 2023-06-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.category'),
            preserve_default=False,
        ),
    ]
