# Generated by Django 4.2.2 on 2023-06-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='votes',
        ),
    ]
